### ISSUE TITLE
Spark 2.3 compatibility?

### ISSUE THREAD

**Issue by flolas** [chermenin/spark-states#11]
Hi!

I wonder if it is compatible with spark 2.3 (current master)

Thank you very much!

**Comment by flolas** [comment]
Doing sbt test with spark 2.3 deps throws:
```
[info] Loading global plugins from /Users/flolas/.sbt/1.0/plugins
[info] Loading project definition from /Users/flolas/Documents/Repositorios/spark-states/project
[info] Loading settings for project spark-states from build.sbt ...
[info] Set current project to spark-states (in build file:/Users/flolas/Documents/Repositorios/spark-states/)
[info] Compiling 3 Scala sources to /Users/flolas/Documents/Repositorios/spark-states/target/scala-2.11/test-classes ...
[info] Done compiling.
[info] RocksDbStateTimeoutSuite:
[info] - no timeout *** FAILED ***
[info]   RocksDbStateStoreHelper.contains(store, "k1") was false (RocksDbStateTimeoutSuite.scala:74)
[info] - statelessness *** FAILED ***
[info]   org.rocksdb.RocksDBException: lock : testdb/LOCK: No locks available
[info]   at org.rocksdb.TtlDB.open(Native Method)
[info]   at org.rocksdb.TtlDB.open(TtlDB.java:87)
[info]   at ru.chermenin.spark.sql.execution.streaming.state.RocksDbStateStoreProvider$RocksDbStateStore.<init>(RocksDbStateStoreProvider.scala:121)
[info]   at ru.chermenin.spark.sql.execution.streaming.state.RocksDbStateTimeoutSuite.createTTLStore(RocksDbStateTimeoutSuite.scala:267)
[info]   at ru.chermenin.spark.sql.execution.streaming.state.RocksDbStateTimeoutSuite.withTTLStore(RocksDbStateTimeoutSuite.scala:45)
[info]   at ru.chermenin.spark.sql.execution.streaming.state.RocksDbStateTimeoutSuite$$anonfun$4.apply$mcV$sp(RocksDbStateTimeoutSuite.scala:87)
[info]   at ru.chermenin.spark.sql.execution.streaming.state.RocksDbStateTimeoutSuite$$anonfun$4.apply(RocksDbStateTimeoutSuite.scala:83)
[info]   at ru.chermenin.spark.sql.execution.streaming.state.RocksDbStateTimeoutSuite$$anonfun$4.apply(RocksDbStateTimeoutSuite.scala:83)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   ...
[info] - processing timeout *** FAILED ***
[info]   org.rocksdb.RocksDBException: lock : testdb/LOCK: No locks available
[info]   at org.rocksdb.TtlDB.open(Native Method)
[info]   at org.rocksdb.TtlDB.open(TtlDB.java:87)
[info]   at ru.chermenin.spark.sql.execution.streaming.state.RocksDbStateStoreProvider$RocksDbStateStore.<init>(RocksDbStateStoreProvider.scala:121)
[info]   at ru.chermenin.spark.sql.execution.streaming.state.RocksDbStateTimeoutSuite.createTTLStore(RocksDbStateTimeoutSuite.scala:267)
[info]   at ru.chermenin.spark.sql.execution.streaming.state.RocksDbStateTimeoutSuite.withTTLStore(RocksDbStateTimeoutSuite.scala:45)
[info]   at ru.chermenin.spark.sql.execution.streaming.state.RocksDbStateTimeoutSuite$$anonfun$5.apply$mcV$sp(RocksDbStateTimeoutSuite.scala:108)
[info]   at ru.chermenin.spark.sql.execution.streaming.state.RocksDbStateTimeoutSuite$$anonfun$5.apply(RocksDbStateTimeoutSuite.scala:104)
[info]   at ru.chermenin.spark.sql.execution.streaming.state.RocksDbStateTimeoutSuite$$anonfun$5.apply(RocksDbStateTimeoutSuite.scala:104)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   ...
[info] - ttl should reset on get, set and update *** FAILED ***
[info]   org.rocksdb.RocksDBException: lock : testdb/LOCK: No locks available
[info]   at org.rocksdb.TtlDB.open(Native Method)
[info]   at org.rocksdb.TtlDB.open(TtlDB.java:87)
[info]   at ru.chermenin.spark.sql.execution.streaming.state.RocksDbStateStoreProvider$RocksDbStateStore.<init>(RocksDbStateStoreProvider.scala:121)
[info]   at ru.chermenin.spark.sql.execution.streaming.state.RocksDbStateTimeoutSuite.createTTLStore(RocksDbStateTimeoutSuite.scala:267)
[info]   at ru.chermenin.spark.sql.execution.streaming.state.RocksDbStateTimeoutSuite.withTTLStore(RocksDbStateTimeoutSuite.scala:45)
[info]   at ru.chermenin.spark.sql.execution.streaming.state.RocksDbStateTimeoutSuite$$anonfun$6.apply$mcV$sp(RocksDbStateTimeoutSuite.scala:127)
[info]   at ru.chermenin.spark.sql.execution.streaming.state.RocksDbStateTimeoutSuite$$anonfun$6.apply(RocksDbStateTimeoutSuite.scala:123)
[info]   at ru.chermenin.spark.sql.execution.streaming.state.RocksDbStateTimeoutSuite$$anonfun$6.apply(RocksDbStateTimeoutSuite.scala:123)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   ...
[info] - different timeouts for each streaming query (states)
[info] RocksDbStateStoreProviderSuite:
[info] - Snapshotting *** FAILED ***
[info]   Set((a,2), (a1,1)) did not equal Set((a,2)) (RocksDbStateStoreProviderSuite.scala:57)
[info] - Cleaning up
[info] - Corrupted snapshots
[info] - Reports metrics
[info] - StateStore.get
[info] Run completed in 2 seconds, 863 milliseconds.
[info] Total number of tests run: 10
[info] Suites: completed 2, aborted 0
[info] Tests: succeeded 5, failed 5, canceled 0, ignored 0, pending 0
[info] *** 5 TESTS FAILED ***
```

**Comment by flolas** [comment]
I tested an old version(last with spark 2.3.1) and it works, but im seeing high processing time(3x than default StateStore provider) and every query is getting more and more. Am I missing something? I need to save ~1M distinct keys in total

Thanks!

**Comment by kant777** [comment]
@flolas Are you still having that issue?
